### ISSUE TITLE
Why would we use both next image and sidepix together? (what does next image not provide)

### ISSUE THREAD

**Issue by algoflows** [neugelb/sidepix#1]
Hi,

Sorry looks like next image and sidepix does the same thing, or even that sidepix has more features than next-image. Which begs the question as to why there is a compatibility layer between sidepix and next-image. Why would we use both together, whats missing from either package to warrant the use of both?

Great work though, lovely package.

Bests,

Sean.

**Comment by abaco** [comment]
Good question!

We created sidepix exactly because next/image wasn't enough for our use cases, so of course I won't be the one recommending next/image for a new project... But if you already have code that relies on next/image and you want to export a fully static site, you can easily delegate the image processing part to sidepix. Later on you might find that the full-fledged `<picture>` component is useful for cases where you need cropping, for instance.

What's missing in sidepix is the frontend features like lazy-loading and styling, but I don't think it makes sense to use next/image unless you plan to use Vercel's or a third-party's image optimization service.

**Comment by algoflows** [comment]
Awesome!

Ok sorry last question. So can use Sidepix instead of next-image in normal react applications (if you see what I am saying).

So, in theory by using Sidepix we can get the same functionality as next-image (and more) in normal react applications and reference remotely hosted somewhere with a URL and the sidepix will fetch, optimize and resize etc..?

Many thanks for the quick response.

Bests, 

Sean.

**Comment by abaco** [comment]
That's the idea 😉

Feel free to ask questions. We know we have to work on documentation and we'll prioritize what we think is least clear or what users will ask.

**Comment by algoflows** [comment]
My biggest confusion is if we can use and optimise remotely hosted images dynamically in any react application. Would be great if it was explicitly mentioned.

**Comment by algoflows** [comment]
Again thanks for the help and clarifying!

**Comment by abaco** [comment]
Thanks for the feedback! Would an additional bullet point under "Features" work? Something like:
> - Processes local images or fetch them from remote host
